global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'smart-money-bot'
    static_configs:
      - targets: ['smart-money-bot:8000']
        labels:
          group: 'app'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
